language: c

compiler:
  - gcc

matrix:
  include:
  - os: osx
    before_deploy:
      - mkdir -p upload && cp boron/boron upload/boron-mac-${TRAVIS_COMMIT:0:7}
    deploy:
      provider: pages
      local_dir: upload
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master

before_script:
  - git clone https://git.code.sf.net/p/urlan/boron/code boron

script:
  - cd boron
  - ./configure --static --thread
  - make
  - make -C test
  - cd ..
